name: CI
on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: turnersapi
  AZURE_WEBAPP_PATH: "."
  NODE_VERSION: "18.12.1"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # - users: actions/checkout
      # - name: Login via AZURE CLI
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{secrets.AZURE_CREDENTIALS}}

      # - name: Checkout source code
      #   uses: actions/checkout@v2
      - name: Checkout
      - uses: actions/setup-node@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: "./pipelines/package.json"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
